.PHONY: all

all: run

run:
	go run server.go conf.go  routes.go controller.go db.go models.go util.go

build:
	go build -v server.go conf.go  routes.go controller.go db.go models.go util.go


# http://azer.bike/journal/a-good-makefile-for-go/
